CREATE DATABASE IF NOT EXISTS CL_generator;
USE CL_generator;

CREATE TABLE IF NOT EXISTS identification (
    Pin INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    First_Name VARCHAR(50),
    Last_Name VARCHAR(50)
    );

CREATE TABLE IF NOT EXISTS profile (
    Pin INT PRIMARY KEY,
    Experience_Level VARCHAR(50),
    Tools TEXT,
    Skills TEXT,
    Link VARCHAR(255),
    Email VARCHAR(100),
    FOREIGN KEY (Pin) REFERENCES identification(Pin) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS coverletter (
    Pin INT PRIMARY KEY,
    Timestamp_CV TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Timestamp_edited TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Location VARCHAR(100),
    FOREIGN KEY (Pin) REFERENCES identification(Pin) ON DELETE CASCADE
    );