services:
  app:
    build: backend/service
    environment:
      - STORAGE_PATH=/app/storage/coverletters/
    volumes:
      - ./storage:/app/storage   # maps local ./storage to /app/storage in container

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: CL_generator
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: